In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("./CSVs/covid_toy.csv",usecols=["gender","cough","city","has_covid"])

In [5]:
df

    gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
..     ...     ...        ...       ...
95  Female    Mild  Bangalore        No
96  Female  Strong    Kolkata       Yes
97  Female    Mild  Bangalore        No
98  Female  Strong     Mumbai        No
99  Female  Strong    Kolkata       Yes

[100 rows x 4 columns]

In [6]:
df.has_covid.value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [7]:
no = 55/100
yes = 45/100

In [8]:
pd.crosstab(df.gender,df.has_covid)

has_covid  No  Yes
gender
Female     34   25
Male       21   20

In [9]:
n_over_female = 34/55
n_over_male = 21/55

y_over_female = 25/45
y_over_male = 20/45

In [10]:
pd.crosstab(df.cough,df.has_covid)

has_covid  No  Yes
cough
Mild       32   30
Strong     23   15

In [11]:
n_over_mild = 32/55
n_over_strong = 23/55

y_over_mild = 30/55
y_over_strong = 15/55

In [12]:
pd.crosstab(df.city,df.has_covid)

has_covid  No  Yes
city
Bangalore  17   13
Delhi      13    9
Kolkata    17   15
Mumbai      8    8

In [13]:
n_over_banglore = 17/55
n_over_delhi = 13/55
n_over_kolkata = 17/55
n_over_mumbai = 8/55

y_over_banglore = 13/45
y_over_delhi = 9/45
y_over_kolkata = 15/45
y_over_mumbai = 8/45

In [15]:
# (Female , Strong, Mumbai )
YES = yes * y_over_female * y_over_strong * y_over_mumbai
print(YES)

0.012121212121212121

In [17]:
NO = no * n_over_female * n_over_strong * n_over_mumbai
print(NO)

0.02068099173553719